리팩토링을 합시다.
jnuro/jedaero pull request #96
Opened 2020-03-14 17:20 UTC by aerain

Closed #95

2020-03-14 18:39 UTC, aerain commented
typescript 적용하였고 일단 약결합 상태로 넣어놓았습니다.

2020-03-14 18:39 UTC, aerain commented
husky를 사용하여 pre-commit에 적용합니다. tslint를 사용하여 rules에 어긋나면 커밋하지 못하게 만듭니다.

2020-03-18 08:21 UTC, WonBeomChoi commented
ts로 리펙토링 개빡세겠네

2020-04-27 12:05 UTC, x86chi commented
> [Roadmap: TSLint -> ESLint · Issue #4534 · palantir/tslint · GitHub](https://github.com/palantir/tslint/issues/4534)

tslint는 작년부터 deprecated 된 도구입니다. `ESlint` 기반의 전환을 권장드립니다.

2020-04-28 05:45 UTC, aerain commented
오우 감사합니다

2020-05-02 09:22 UTC, x86chi commented on index.tsx
> +export default StoryBook;
root 컴포넌트에서 storybook 모듈은 왜 내보내시는가요?

2020-05-02 09:36 UTC, mu-hun requested changes

2020-05-02 09:36 UTC, x86chi commented on src/JedaeroContainer.tsx
> +import { JedaeroStackNavigator } from '@sqd-ffrog/jedaero-navigator';
(README를 추가했다는) 커밋 타이틀과 달리 80%가 홑따옴표로 단순 수정이고 20%가 린터 설정 업데이트입니다. 두가지 사항을 별도의 커밋으로 분리하는 것을 권해드립니다.

> [Atomic Commits in the Command Line with Git](https://seesparkbox.com/foundry/atomic_commits_with_git)

2020-05-02 10:15 UTC, aerain commented on src/JedaeroContainer.tsx
> +import { JedaeroStackNavigator } from '@sqd-ffrog/jedaero-navigator';
원래 방침으로라면 당연히 그렇게 해야되는게 맞습니다 좋은 지적 감사합니다

다만 커밋의 의미와는 별개로 홀수 따옴표 커밋등이 디버깅을 위한 트레이싱에 방해가 될정도로 크게 문제가 되진 않는다고 판단해서 해당 커밋 일단 유지해둘 생각입니당. 

애초에 이 pr에 들어있는 커밋들 자체가 이미 알려주신 레퍼런스들하곤 이미 너무 동떨어져 버린 경향성이 커서 이후 pr들에 해당 가이드 맞춰도 좋을것 같군요 😄

2020-05-02 10:16 UTC, aerain commented on index.tsx
> +export default StoryBook;
이거 스토리북 테스트용으로 임의로 넣어본 넘입니다. pr 승인 시점에서는 이거 뺄 예정입니다 👍🏼

2020-05-02 10:20 UTC, aerain commented on index.tsx
> +export default StoryBook;
그리고 제가 요즘 프론트 안건들기도 해서 스토리북 부분은 잘 모르겠네요 😢
나중에 이거 머지 되고나서 관련 컴포넌트 등록하는 pr 따로 해주셔도 좋을 것 같아요

@x86chi

2020-05-02 14:02 UTC, x86chi commented on src/JedaeroContainer.tsx
> +import { JedaeroStackNavigator } from '@sqd-ffrog/jedaero-navigator';
제 생각에는 지금이라도 개선되지 않으면 부채가 덜어지기에는 어려울 것 같습니다 🤔 

버전 관리 시스템은 수정 내역을 보다 의미있게 관리하기 위해 사용하는 것입니다.

가장 최근 내역이라도 git reset 작업으로 되돌린 뒤 force-push 해보시면 어떨까요?

```
git reset --mixed HEAD^1
```

이전(2ed7886)으로 되돌리되, 수정 사항은 unstaging 상태로 만들고, storybook 코드 제거

```
git add <linters paths>
git commit // Update linter
git commit // Replace double quote to single
git push -f
```

2020-05-02 14:05 UTC, x86chi commented on index.tsx
> +export default StoryBook;
storybook 은 디자인 시스템을 관리하는 용도로 사용하기 때문에

제가 디자이너 분의 본래 의도가 담긴 UI 목업을 갖고 있지 않은 이상 어렵네요 😢

2020-05-02 17:03 UTC, aerain commented on src/JedaeroContainer.tsx
> +import { JedaeroStackNavigator } from '@sqd-ffrog/jedaero-navigator';
흠 34478bc 커밋내역은 확실히 readme.md에 대한 내용이 맞는 것으로 판단되네요. 🤔

중간 tslint -> eslint 교체과정에서의 일부 린터 수정에 관한 내역이 끼어있어 커밋 메시지와 일치하지 않는 것은 확실하게 부채이긴 합니다만, 이 건에 대해서는 그냥 넘기도록 하겠습니다. 

storybook의 경우는 force-push없이 따로 제가 revert 하는 커밋으로 진행하도록 하겠습니다.

2021-11-30 12:50 UTC, closed without merging